// ============================================================
// CodexProvider — spawn `codex exec --json`, parse JSONL
//
// 基于 M0 实测（Codex CLI v0.139.0）:
//   - codex exec <prompt> --json
//   - codex exec resume <tid> <prompt> --json
//   - thread_id 是 UUID 格式顶层字段
//   - --ask-for-approval CLI flag 不存在，审批策略在 config.toml
//
// 跟踪: [#23](https://github.com/AINIZE-SPACE/chorusgate/issues/23)
// ============================================================

import { spawn } from "node:child_process";
import { writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { CodexEventParser } from "./codex-parser.js";
import type {
  AgentProvider,
  CreateSessionOptions,
  ResumeSessionOptions,
  SessionOutput,
} from "./types.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const projectRoot = resolve(__dirname, "..", "..");

const CODEX_BIN = process.env.CODEX_BIN || "codex";

function spawnCodex(
  args: string[],
  prompt: string,
  cwd: string,
  timeoutMs: number,
  parser: CodexEventParser,
): Promise<SessionOutput> {
  return new Promise<SessionOutput>((resolve) => {
    const win = process.platform === "win32";
    const cmd = win
      ? `"${CODEX_BIN}" ${args
          .map((a) => (a.includes(" ") ? `"${a}"` : a))
          .join(" ")}`
      : CODEX_BIN;
    const spawnArgs = win ? [] : args;
    const child = spawn(cmd, spawnArgs, {
      cwd,
      stdio: ["pipe", "pipe", "pipe"],
      shell: win,
      windowsHide: true,
    });

    // codex exec reads prompt from argv; stdin for pipe-only mode
    if (prompt) {
      child.stdin.write(prompt);
      child.stdin.end();
    }

    let stdoutBuf = "";
    let stderr = "";
    let settled = false;

    const timer = setTimeout(() => {
      if (settled) return;
      settled = true;
      child.kill("SIGKILL");
      resolve({
        ok: false,
        text: "",
        sessionId: "",
        error: `codex exec timed out after ${timeoutMs}ms`,
      });
    }, timeoutMs);

    child.stdout.on("data", (chunk) => {
      stdoutBuf += chunk.toString();
      const lines = stdoutBuf.split("\n");
      stdoutBuf = lines.pop() ?? "";
      for (const line of lines) parser.feed(line);
    });

    child.stderr.on("data", (chunk) => {
      stderr += chunk.toString();
    });

    child.on("error", (err) => {
      if (settled) return;
      settled = true;
      clearTimeout(timer);
      resolve({
        ok: false,
        text: "",
        sessionId: "",
        error: `failed to spawn codex: ${err.message}`,
      });
    });

    child.on("close", (code) => {
      if (settled) return;
      settled = true;
      clearTimeout(timer);

      if (stdoutBuf) parser.feed(stdoutBuf);

      const text = parser.getResultText();
      if (code === 0 && text) {
        resolve({ ok: true, text, sessionId: "" });
      } else if (code === 0 && !text) {
        resolve({
          ok: false,
          text: "",
          sessionId: "",
          error: "codex exec exited 0 but produced no output",
        });
      } else {
        resolve({
          ok: false,
          text,
          sessionId: "",
          error: `codex exec exited ${code}: ${stderr.trim().slice(0, 500)}`,
        });
      }
    });
  });
}

export const codexProvider: AgentProvider = {
  id: "codex",
  bin: CODEX_BIN,

  /** Generate a TOML MCP config for Codex (STORY-7). */
  generateMCPConfig(botToken?: string, appToken?: string): string {
    const effectiveBot = botToken || process.env.SLACK_BOT_TOKEN || "";
    const effectiveApp = appToken || process.env.SLACK_APP_TOKEN || "";
    const cacheKey = effectiveBot.slice(0, 8);
    const configPath = resolve(
      projectRoot, "config", `codex-mcp-${cacheKey}.generated.toml`,
    );
    const senderBin = resolve(projectRoot, "bin", "chorusgate-mcp.mjs");

    // TOML format — Codex uses TOML for config, unlike CC's JSON.
    const toml = [
      "# Codex MCP config — auto-generated by ChorusGate",
      `# Generated at: ${new Date().toISOString()}`,
      "",
      "[mcp_servers.slack]",
      'command = "node"',
      `args = ["${senderBin.replace(/\\/g, "\\\\")}"]`,
      "",
      "[mcp_servers.slack.env]",
      `SLACK_BOT_TOKEN = "${effectiveBot}"`,
      `SLACK_APP_TOKEN = "${effectiveApp}"`,
      "",
      "# Headless mode: auto-approve MCP tool calls",
      'default_tools_approval_mode = "approve"',
      "",
    ].join("\n");

    try {
      writeFileSync(configPath, toml);
    } catch (err) {
      console.error(
        "[codex-provider] WARNING: could not write Codex MCP config:",
        (err as Error).message,
      );
    }

    return configPath;
  },

  async createSession(
    prompt: string,
    opts: CreateSessionOptions,
  ): Promise<SessionOutput> {
    // Codex: session ID 后解析（从 JSONL thread.started.thread_id）
    let resolvedSessionId = "";
    const args = ["exec", prompt, "--json"];

    const parser = new CodexEventParser();
    parser.onProgress = opts.onProgress;
    parser.onSessionId = (tid) => {
      resolvedSessionId = tid;
      opts.onSessionId?.(tid);
    };

    const result = await spawnCodex(
      args,
      "",
      opts.cwd,
      opts.timeoutMs,
      parser,
    );

    return { ...result, sessionId: resolvedSessionId };
  },

  async resumeSession(
    prompt: string,
    sessionId: string,
    opts: ResumeSessionOptions,
  ): Promise<SessionOutput> {
    // codex exec resume <thread_id> <prompt> --json
    const args = ["exec", "resume", sessionId, prompt, "--json"];

    const parser = new CodexEventParser();
    parser.onProgress = opts.onProgress;

    return spawnCodex(args, "", opts.cwd, opts.timeoutMs, parser).then((r) => ({
      ...r,
      sessionId,
    }));
  },
};
